# PlatformIO pre-build script: writes include/build_info.h with the git
# commit and build time, shown on the web page as the firmware version.
import datetime
import os
import subprocess

Import("env")  # noqa: F821 (provided by PlatformIO)


def git(*args):
    try:
        return subprocess.check_output(["git", *args], cwd=env["PROJECT_DIR"], stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        return ""


commit = git("rev-parse", "--short", "HEAD") or "sconosciuto"
if git("status", "--porcelain", "--untracked-files=no"):
    commit += "+modifiche"
built = datetime.datetime.now().strftime("%d/%m/%Y %H:%M")
header = f'''#pragma once
// Generated by scripts/build_info.py at every build - do not edit.
#define FIRMWARE_COMMIT "{commit}"
#define FIRMWARE_BUILT "{built}"
'''
path = os.path.join(env["PROJECT_DIR"], "include", "build_info.h")
old = open(path).read() if os.path.exists(path) else ""
if old != header:
    with open(path, "w") as f:
        f.write(header)
