# PlatformIO pre-build script: turns content/frasi_dell_ora.txt (one quote
# per line, UTF-8) into include/quotes_builtin.h, the built-in list of the
# "Frase dell'ora" mode. Edit the text file, not the header.
import os

Import("env")  # noqa: F821 (provided by PlatformIO)

source = os.path.join(env["PROJECT_DIR"], "content", "frasi_dell_ora.txt")
with open(source, encoding="utf-8") as f:
    lines = [line.strip() for line in f if line.strip()]


def c_string(text):
    out = ""
    for byte in text.encode("utf-8"):
        ch = chr(byte)
        if ch == "\\" or ch == '"':
            out += "\\" + ch
        elif 32 <= byte < 127:
            out += ch
        else:
            out += "\\%03o" % byte  # octal: never swallows the next character
    return out


body = "\n".join('    "%s\\n"' % c_string(line) for line in lines)
header = f'''#pragma once
// Generated by scripts/quotes.py from content/frasi_dell_ora.txt - do not edit.
// {len(lines)} quotes, one per line.
static const char BUILTIN_QUOTES[] =
{body};
'''
path = os.path.join(env["PROJECT_DIR"], "include", "quotes_builtin.h")
old = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
if old != header:
    with open(path, "w", encoding="utf-8") as f:
        f.write(header)
