# PlatformIO pre-build script: builds the control page from web/page.html,
# web/style.css and web/app.js (the CSS and JS inlined, so the page is a
# single request), gzips it and writes include/webpage.h. Edit the files in
# web/, not the header.
import gzip
import os

Import("env")  # noqa: F821 (provided by PlatformIO)

root = env["PROJECT_DIR"]


def read(name):
    with open(os.path.join(root, "web", name), encoding="utf-8") as f:
        return f.read()


page = read("page.html")
page = page.replace("/*STYLE*/", "\n" + read("style.css"), 1)
page = page.replace("/*SCRIPT*/", "\n" + read("app.js"), 1)
data = gzip.compress(page.encode("utf-8"), compresslevel=9, mtime=0)

rows = []
for i in range(0, len(data), 20):
    rows.append("    " + ", ".join("0x%02x" % b for b in data[i:i + 20]) + ",")
header = """#pragma once
// Generated by scripts/webpage.py from web/ - do not edit.
// %d bytes of page, %d gzipped.
#include <Arduino.h>
static const uint8_t WEBPAGE_GZ[] PROGMEM = {
%s
};
static const size_t WEBPAGE_GZ_LEN = sizeof(WEBPAGE_GZ);
""" % (len(page.encode("utf-8")), len(data), "\n".join(rows))

path = os.path.join(root, "include", "webpage.h")
old = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
if old != header:
    with open(path, "w", encoding="utf-8") as f:
        f.write(header)
